CREATE TABLE scopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    CONSTRAINT uk_scopes_name UNIQUE (name)
);

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(100) NOT NULL,
    client_secret VARCHAR(200),
    name VARCHAR(200) NOT NULL,
    client_type VARCHAR(20) NOT NULL,
    access_token_ttl_seconds BIGINT NOT NULL,
    refresh_token_ttl_seconds BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_clients_client_id UNIQUE (client_id)
);

CREATE TABLE client_redirect_uris (
    client_id BIGINT NOT NULL,
    redirect_uri VARCHAR(500) NOT NULL,
    PRIMARY KEY (client_id, redirect_uri),
    CONSTRAINT fk_client_redirect_uris_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

CREATE TABLE client_grant_types (
    client_id BIGINT NOT NULL,
    grant_type VARCHAR(30) NOT NULL,
    PRIMARY KEY (client_id, grant_type),
    CONSTRAINT fk_client_grant_types_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

CREATE TABLE client_scopes (
    client_id BIGINT NOT NULL,
    scope_id BIGINT NOT NULL,
    PRIMARY KEY (client_id, scope_id),
    CONSTRAINT fk_client_scopes_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
    CONSTRAINT fk_client_scopes_scope FOREIGN KEY (scope_id) REFERENCES scopes(id) ON DELETE CASCADE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(200) NOT NULL,
    email VARCHAR(200),
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE authorization_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(200) NOT NULL,
    client_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    redirect_uri VARCHAR(500) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_authorization_codes_code UNIQUE (code),
    CONSTRAINT fk_authorization_codes_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
    CONSTRAINT fk_authorization_codes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE authorization_code_scopes (
    authorization_code_id BIGINT NOT NULL,
    scope VARCHAR(100) NOT NULL,
    PRIMARY KEY (authorization_code_id, scope),
    CONSTRAINT fk_authorization_code_scopes_code FOREIGN KEY (authorization_code_id) REFERENCES authorization_codes(id) ON DELETE CASCADE
);

CREATE TABLE access_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_value VARCHAR(2000) NOT NULL,
    client_id BIGINT NOT NULL,
    user_id BIGINT,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_access_tokens_token_value UNIQUE (token_value),
    CONSTRAINT fk_access_tokens_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
    CONSTRAINT fk_access_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE access_token_scopes (
    access_token_id BIGINT NOT NULL,
    scope VARCHAR(100) NOT NULL,
    PRIMARY KEY (access_token_id, scope),
    CONSTRAINT fk_access_token_scopes_token FOREIGN KEY (access_token_id) REFERENCES access_tokens(id) ON DELETE CASCADE
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_value VARCHAR(200) NOT NULL,
    client_id BIGINT NOT NULL,
    user_id BIGINT,
    access_token_id BIGINT,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_refresh_tokens_token_value UNIQUE (token_value),
    CONSTRAINT fk_refresh_tokens_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_tokens_access_token FOREIGN KEY (access_token_id) REFERENCES access_tokens(id) ON DELETE SET NULL
);

CREATE TABLE refresh_token_scopes (
    refresh_token_id BIGINT NOT NULL,
    scope VARCHAR(100) NOT NULL,
    PRIMARY KEY (refresh_token_id, scope),
    CONSTRAINT fk_refresh_token_scopes_token FOREIGN KEY (refresh_token_id) REFERENCES refresh_tokens(id) ON DELETE CASCADE
);

CREATE INDEX idx_authorization_codes_client ON authorization_codes(client_id);
CREATE INDEX idx_access_tokens_client ON access_tokens(client_id);
CREATE INDEX idx_refresh_tokens_client ON refresh_tokens(client_id);
